# Generated by Django 5.0.3 on 2024-05-29 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='goodVideo',
            field=models.FileField(upload_to='videos'),
        ),
    ]
